### ISSUE TITLE
Confusion of  I(X; S,Y)

### ISSUE THREAD

**Issue by Ching-Nam** [PanZiqiAI/disentangled-information-bottleneck#2]
Dear author,
  Thanks for your great work! I am a bit confused about how you transform the label into class embbeding. Specifically, can you explain how the code below works? Does it basically learn a trainable matrix from the label? Thank you very much.
`class_emb = torch.index_select(self.word_dict, dim=0, index=class_label)
class_emb = F.leaky_relu_(self._fc_class(class_emb), negative_slope=0.2)`

**Comment by PanZiqiAI** [comment]
Thanks for your question! Taking the MNIST dataset with 10 class labels as an example,  ``` self.word_dict ``` is a ```10 x emb_dim``` trainable matrix, where ```emb_dim``` is the embedding dimension. Namely, we set up one class embedding vector for each class. Therefore, given a ```class_label``` (an integer of 0~9), ```torch.index_select(self.word_dict, dim=0, index=class_label)``` gives the class embedding of ```class_label```.
